---
# Based on:
# - https://magpi.raspberrypi.org/articles/make-a-raspberry-pi-audio-player-with-mopidy-music
# - https://magpi.raspberrypi.org/articles/build-a-home-music-system-with-raspberry-pi
# And can be augmented with:
# - https://magpi.raspberrypi.org/articles/build-a-multi-room-audio-system-with-raspberry-pi

- name: Setup screen orientation /boot/config.txt
  lineinfile:
    path: /boot/config.txt
    regexp: "^ *#?lcd_rotate"
    line: "lcd_rotate=2"
  when:
    - jukebox__configure
    - not jukebox__headless

# Create powermgmt off service
- name: Create power management systemd service file
  copy:
    src: wifi-power-mgmt.service
    dest: /etc/systemd/system/wifi-power-mgmt.service
  register: powermgmt_service
  when:
    - jukebox__configure

# Create autoplay service
- name: Create autoplay systemd service file
  template:
    src: autoplay.service
    dest: /etc/systemd/system/autoplay.service
  register: autoplay_service
  notify: Daemon reload
  when:
    - jukebox__configure
    - jukebox__autoplay_random|default(False)

# Create checkplaylist service
- name: Create checkplaylist systemd service file
  template:
    src: checkplaylist.service
    dest: /etc/systemd/system/checkplaylist.service
  register: checkplaylist_service
  notify: Daemon reload
  when:
    - jukebox__configure
    - jukebox__autoplay_random|default(False)

# Create checkplaylist timer
- name: Create checkplaylist systemd timer file
  template:
    src: checkplaylist.timer
    dest: /etc/systemd/system/checkplaylist.timer
  register: checkplaylist_timer
  notify: Daemon reload
  when:
    - jukebox__configure
    - jukebox__autoplay_random|default(False)

- name: Start power-management service if created
  service:
    name: wifi-power-mgmt.service
    state: restarted
  when: powermgmt_service is changed

- name: disable pulseaudio service when headless
  service:
    name: pulseaudio.service
    state: stopped
    enabled: False
  when:
    - jukebox__headless

# - name: disable pulseaudio socket when headless
#   service:
#     name: pulseaudio.socket
#     enabled: False
#   when:
#     - jukebox__headless

- name: Cancel splash rainbow /boot/config.txt
  lineinfile:
    path: /boot/config.txt
    regexp: "^ *#?disable_splash"
    line: "disable_splash=1"
  when:
    - jukebox__configure
    - not jukebox__headless
  
# - name: Change tty for boot-log
#   shell:
#     cmd: "sed -i -e 's/console=tty1/console=tty3/' /boot/cmdline.txt"
#   when: jukebox__configure

- name: Add mopidy apt key
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present
  when: jukebox__install

- name: Add mopidy repository
  apt_repository:
    filename: mopidy
    repo: deb https://apt.mopidy.com/ bullseye main contrib non-free
    update_cache: false
    state: present
  register: mopidy_repo
  when: jukebox__install

- name: Update repo now
  apt:
    update_cache: true
  when:
    - jukebox__install
    - mopidy_repo is changed

- name: Jukebox install common packages
  apt:
    name: "{{ jukebox__headless_default_packages }}"
    update_cache: yes
    state: present
  when:
    - jukebox__configure

- name: Jukebox install non headless packages
  apt:
    name: "{{ jukebox__default_packages }}"
    update_cache: yes
    state: present
  when:
    - jukebox__configure
    - not jukebox__headless

- name: Video group membership for user mopidy
  user:
    name: mopidy
    groups: video
    append: yes
  when: jukebox__install
  notify: Restart mopidy

- name: Enable mopidy service
  service:
    name: mopidy
    enabled: yes
  when: jukebox__configure
  notify: Restart mopidy

- name: Configure mopidy
  template:
    src: mopidy.conf
    dest: /etc/mopidy/mopidy.conf
  when: jukebox__configure
  notify:
    - Restart mopidy
    - Rescan mopidy

- name: Install some mopidy plugins
  pip:
    name:
      - Mopidy-Iris
      - Mopidy-Local
      - Mopidy-RadioNet
      - Mopidy-SomaFM
      # - Mopidy-Podcast
      # - Mopidy-Podcast-iTunes
      # - Mopidy-SoundCloud # Need conf: https://mopidy.com/ext/soundcloud
      # - Mopidy-YouTube # Need conf [youtube] enabled = true
      # - Mopidy-InternetArchive
      # - Mopidy-Party # For sharing access to friends
  when:
    - jukebox__install
    - jukebox__bug_fixed is defined

- name: Install some mopidy non headless plugins
  pip:
    name:
      - Mopidy-Iris
  when:
    - jukebox__install
    - not jukebox__headless
    - jukebox__bug_fixed is defined

- name: Update sudoer mechanism for mopidy
  template:
    src: sudomopidy
    dest: /etc/sudoers.d/02-sudo-mopidy
    validate: 'visudo -cf %s'
  when: jukebox__install
  notify: Restart mopidy

- name: Setup kiosk script
  template:
    src: kiosk.sh
    dest: "/home/{{ jukebox__default_user }}/kiosk.sh"
    owner: "{{ jukebox__default_user }}"
    group: "{{ jukebox__default_user }}"
    mode: 0755
  when:
    - jukebox__configure
    - not jukebox__headless

- name: Setup autoplay script
  template:
    src: autoplay.sh
    dest: "/home/{{ jukebox__default_user }}/autoplay.sh"
    owner: "{{ jukebox__default_user }}"
    group: "{{ jukebox__default_user }}"
    mode: 0755
  when:
    - jukebox__configure
    - jukebox__autoplay_random|default(False)

- name: Setup addtracks script
  template:
    src: addtracks.sh
    dest: "/home/{{ jukebox__default_user }}/addtracks.sh"
    owner: "{{ jukebox__default_user }}"
    group: "{{ jukebox__default_user }}"
    mode: 0755
  when:
    - jukebox__configure
    - jukebox__autoplay_random|default(False)

- name: Setup checkplaylist script
  template:
    src: checkplaylist.sh
    dest: "/home/{{ jukebox__default_user }}/checkplaylist.sh"
    owner: "{{ jukebox__default_user }}"
    group: "{{ jukebox__default_user }}"
    mode: 0755
  when:
    - jukebox__configure
    - jukebox__autoplay_random|default(False)

- name: Setup refillkey script
  template:
    src: refillkey.sh
    dest: "/home/{{ jukebox__default_user }}/refillkey.sh"
    owner: "{{ jukebox__default_user }}"
    group: "{{ jukebox__default_user }}"
    mode: 0755
  when:
    - jukebox__configure
    - jukebox__refill|default(False)

- name: Configure user autologin
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: "^#autologin-user="
    line: "autologin-user={{ jukebox__default_user }}"
  when:
    - jukebox__configure
    - not jukebox__headless
  # notify: Restart musicbox

- name: Configure user autologin timeout
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: "^#autologin-user-timeout="
    line: "autologin-user-timeout=0"
  when:
    - jukebox__configure
    - not jukebox__headless
  # notify: Restart musicbox

# TODO: Should manage (/etc/xdg|~/.config)/lxsession/LXDE/autostart - Contains normally:
# @lxpanel --profile LXDE
# @pcmanfm --desktop --profile LXDE
# @xscreensaver -no-splash

# TODO: Should manage ~/.config/autostart/kioskmode.desktop - should contain
# [Desktop Entry]
# Type=Application
# Exec=/home/francois/kiosk.sh

- name: Start autoplay service if created
  service:
    name: autoplay.service
    state: restarted
    enabled: yes
  when:
    - autoplay_service is changed
    - jukebox__autoplay_random|default(False)

- name: Start checkplaylist service if created
  service:
    name: checkplaylist.service
    state: restarted
    enabled: yes
  when:
    - checkplaylist_timer is changed
    - jukebox__autoplay_random|default(False)

- name: Start checkplaylist timer if created
  service:
    name: checkplaylist.timer
    state: restarted
    enabled: yes
  when:
    - checkplaylist_timer is changed
    - jukebox__autoplay_random|default(False)

- name: PulseAudio TCP setup
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: "^#load-module module-native-protocol-tcp"
    line: "load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1"
  when:
    - jukebox__configure
    # - not jukebox__headless
  # notify: Restart musicbox

- name: PulseAudio unload suspend-on-idle on setup
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: "^load-module module-suspend-on-idle"
    line: "#load-module module-suspend-on-idle"
  when:
    - jukebox__configure
    # - not jukebox__headless
  # notify: Restart musicbox
